### ISSUE TITLE
Why cache could be optional

### ISSUE THREAD

**Issue by garex** [php-fig/cache-util#11]
As I understand, psr/cache dont' want to accept the idea of _cache optionality_. I will try to explain why optinality is a good idea.

Ok, let's talk about MySQL server.

As far as I'm concerned, MySQL server is good example of proper design.

According to [this article](http://dev.mysql.com/doc/refman/5.7/en/query-cache-configuration.html) you may see that cache is optional. It doesn't matter whereas user enabled it or not. The result of the query will be the same in any case.

It means that [null-cache](https://en.wikipedia.org/wiki/Null_Object_pattern#Motivation) is a good idea.

From user's point of view the cache is not always needed. It's an optimization, infrastructure layer tool. When we design system -- we dont' start from optimization, we start from domain logic and then after some time, when we find bottlenecks, we optimize 'em. So from scratch we allow class's user to use it without any cache-setup issues out of the box. It's a friendly design. Same as we see in great PSR/Log.

Testability of objects with injected cache is an issue. What it should take? Some real pre-cleaned cache pool or home-grown null implementation?

The main advantage of null object implementation is that it's behaviour is `do nothing`. In case of cache pool it's just `never hit/get/save` behaviour. There is one way to do it.

**Comment by michaelcullum** [comment]
Did you mean to add this to #10?

**Comment by garex** [comment]
And to #9 also.

**Comment by garex** [comment]
[PSR-6 recommendation](http://www.php-fig.org/psr/psr-6/#error-handling) states:

> While caching is often an important part of application performance, it should never be a critical part of application functionality.

This is another +1 to why cache is an optional dependecy.
